# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  schedule:
    # - cron: '50 17 * * Fri'
    - cron: '*/5 * * * *'
  push:
    branches: [ "*" ]

jobs:
  push_to_registry:
    name: Push to Docker Hub
    strategy:
      fail-fast: false
      matrix:
        os: ['debian:10']
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Set env variables default_os, base_image_name, image_name, latest_image_name
        run: |
          echo "default_os=debian" >> $GITHUB_ENV
          echo "base_image_name=library/${{ matrix.os }}" >> $GITHUB_ENV
          echo "image_name=${{ secrets.DOCKER_USERNAME }}/collectd:${{ matrix.os }}" >> $GITHUB_ENV
          echo "latest_image_name=${{ secrets.DOCKER_USERNAME }}/collectd:latest" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Check if original image update is available
        id: base_image_update_check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: ${{ env.base_image_name }}
          image: ${{ env.image_name }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        if: ( github.event_name != 'schedule' || steps.base_image_update_check.outputs.needs-updating == 'true' )
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image 1.0
        uses: docker/build-push-action@v3
        if: ( github.event_name != 'schedule' || steps.base_image_update_check.outputs.needs-updating == 'true' )
        with:
          context: .
          push: ${{ github.ref_name == 'main' }}
          build-args: BASE_IMAGE=${{ env.base_image_name }}
          tags: |
            ${{ env.image_name }}-1.0
            ${{ env.image_name }}-1
            ${{ env.image_name }}
          target: v1_0

      - name: Build and push Docker image latest
        uses: docker/build-push-action@v3
        if: ( github.event_name != 'schedule' || steps.base_image_update_check.outputs.needs-updating == 'true' ) && matrix.os == env.default_os
        with:
          context: .
          push: ${{ github.ref_name == 'main' }}
          build-args: PHP_IMAGE=${{ env.base_image_name }}
          tags: ${{ env.latest_image_name }}
          target: latest
