# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  schedule:
    - cron: '20 18 * * *'
  push:
    branches: [ "*" ]

jobs:
  push_to_registry:
    name: Push to Docker Hub
    strategy:
      fail-fast: false
      matrix:
        php_version: [5.6, 7.2, 7.4, 8.1]
        web_server: ["", "-apache"]
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, linux, x64]
    environment: production
    steps:
      - name: Set env variable image_name
        run: echo "image_name=${{ secrets.DOCKER_USERNAME }}/php:${{ matrix.php_version }}${{ matrix.web_server }}" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image 1.2
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref_name == 'main' }}
          build-args: |
            PHP_IMAGE_TAG=${{ matrix.php_version }}${{ matrix.web_server }}
          tags: |
            ${{ env.image_name }}-1.2
          target: v1_2

      - name: Build and push Docker image 1.3
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref_name == 'main' }}
          build-args: |
            PHP_IMAGE_TAG=${{ matrix.php_version }}${{ matrix.web_server }}
          tags: |
            ${{ env.image_name }}-1.3
            ${{ env.image_name }}-1
            ${{ env.image_name }}
          target: v1_3
